### PR TITLE
Default to mine tab after document creation

### PR DESCRIPTION
**Pull request by timdunn22**
## What this PR does?
1. Default to mine tab after document creation

## How to test?
1. Go to http://cove-staging.herokuapp.com/documents new after signing in
2. Create a new document
3. Check to see if you are on the mine tab

### CODE REVIEW

**Comment by SteveMarvin** [comment]
Nope, sorry, I was returned to the Shared tab.

**Comment by jamiefolsom** [comment]
@timdunn22 Please respond to Steve's feedback first, then I'll review code. Thanks.

**Comment by timdunn22** [comment]
@SteveMarvin Try this again it should work now.

**Comment by SteveMarvin** [comment]
👍

**Pull request merged**
