### PR TITLE
added NAVSA SSO through omniauth

### LINKED ISSUE #15: As a NAVSA member, I want to sign into navsa.org and get access to ANS
- navsa.org is a wordpress site -- it would be the OAuth provider in this case.
- studio.covecollective.org is the rails app running on heroku -- it would be a client.
- accounts only exist in navsa -- can we offer a "Sign up with navsa account" option that creates an AS user account?
- Wildcard cert for covecollective.org has been purchased -- need to verify same cert can be used with www.covecollective.org as well (Drupal app on pantheon).

### PR DESCRIPTION
**Pull request by akstuhl**
#### What are the relevant tickets?
closes #15

#### What's this PR do?
Integrates a single-sign-on tool into Cove Studio, allowing users to log in through the NAVSA Wordpress site. Logging in through NAVSA is prioritized in the UI to indicate that it's the default way to access Cove Studio. If a user has an existing Cove Studio account with the same email address as their NAVSA account, that account will be automatically linked when they click 'Log in through NAVSA'.

#### How should this be manually tested?
Create an account at http://navsa.org, then visit the [PR review app](https://cove-staging-pr-74.herokuapp.com/), click "Log in", then click "Log in through NAVSA"

#### Notes
- In this first pass, email is treated as a reliable unique identifier - i.e., when you click "Log in through NAVSA", the app will link your NAVSA account to an existing account with the same email. Is that a good approach? We could require that you first be signed in to both accounts (rather than just  in order for the link to be made, if that would give additional security.
- When linking a NAVSA account to an existing account, what information should be overwritten? (e.g. first and last name).
- When a user with no pre-existing account first logs in through NAVSA, an account will be created for them. Currently, this bypasses the email confirmation (seems unnecessary if they're already logged in to NAVSA) but also the user agreement. Should there be an intermediary step where new users must accept the user agreement before a first-time authentication completes?

### CODE REVIEW

**Comment by jamiefolsom** [comment]
H @akstuhl Code looks good. Assigning to @SteveMarvin for testing.

**Comment by SteveMarvin** [comment]
> Create an account at http://navsa.org, then visit the PR review app, click "Log in", then click "Log in through NAVSA"

I cannot create an account at NAVSA for testing as it requires payment. <turns pockets inside out>

**Comment by jamiefolsom** [comment]
@akstuhl -- would you create an account for @SteveMarvin on navsa.org? Thanks!

**Comment by akstuhl** [comment]
just added a NAVSA account for Steve

**Comment by SteveMarvin** [comment]
This worked just fine for me. Unfortunately, given that I need to have an account created by Jamie or Andy, it becomes difficult for me to test this multiple times, or across multiple browsers, since once I have logged in once, my account is linked. That's probably not necessary for something as simple as this, but it is a testing constraint. 

If you guys would like me to do that more extensive testing, please create me a series of test accounts such as this:

- steve+test01@performantsoftware.com
- steve+test01@performantsoftware.com
- steve+test01@performantsoftware.com
- steve+test01@performantsoftware.com
- steve+test01@performantsoftware.com

**Comment by akstuhl** [comment]
Hi @SteveMarvin, sorry, meant to make yours an admin account on first pass - I just updated it to admin, so you should now be able to create new accounts

**Comment by SteveMarvin** [comment]
Sweet!

**Comment by SteveMarvin** [comment]
I have to ask, though, what kind of twisted monster creates a password that contains both uppercase i’s and lowercase L’s? 😖

**Comment by SteveMarvin** [comment]
Successfully tested on multiple browsers.

**Comment by jamiefolsom** [comment]
Hey @akstuhl, looks like this is good to merge!

**Comment by akstuhl** [comment]
Thanks @jamiefolsom, will do!

**Pull request merged**
