### PR TITLE
Fixed issue where document snapshot can't be saved

### LINKED ISSUE #312: "Save document for export" not working
Freezes on ‘creating snapshot’ -- see errors in js console.

404s for user.json, etc when using `/anthologies/` URL; 500 errors on the `/documents/` URL

https://github.com/performant-software/Annotation-Studio/blob/master/config/routes.rb#L52

https://github.com/performant-software/Annotation-Studio/blob/master/app/assets/javascripts/snapshot.js#L64

### PR DESCRIPTION
**Pull request by timdunn22**
### What does this PR do?
1. Fixes the issue with the errors in the javascript console blocking creating a snapshot
2. Closes #312 
## How to test?
1. Login and go to https://cove-studio-issue-312-apacegmu.herokuapp.com/users/sign_in#email-login
2. Click on dashboard and then click on any document under the mine tab
3. Click on the Save Document on the Annotations sidebar
4. Check to make sure the javascript console doesn't have any error messages
5. Go back to the dashboard and click on anthologies
6. Add a document you own to an anthology
7. Click on the document show link
8. Repeat 3 and 4

### CODE REVIEW

**Comment by SteveMarvin** [comment]
Worked great until I clicked on the document that was in my anthology. Got the spinner hung up
image
and the following console error: 

image

**Comment by timdunn22** [comment]
@SteveMarvin Try this again. See if in the javascript console you see the words "Saved Snapshot"

**Comment by SteveMarvin** [comment]
👍

**Comment by jamiefolsom** [comment]
@timdunn22 merge to master.

**Pull request merged**
