### PR TITLE
Now users can search for users assigned to anthologies by email and full name

### PR DESCRIPTION
**Pull request by timdunn22**
## What this PR will accomplish
1. Admins will be able to search for users in the anthology show view and able to add them or remove them from anthologies 

# How to test
1. Login to http://cove-staging.herokuapp.com/ (user your admin account)
2. On dashboard page click on the Anthologies page at http://cove-staging.herokuapp.com/anthologies
3. Now click on any anthology from list for detail view
4. Click on the users tab
5. Try to search for a full name (You can use fuzzy search here and on the next PR case insensitive searches will be enabled as well)
6. After you find a user assign them to an anthology and click on the all tab to verify they are on the all list
7. Try to remove them from the anthology and make sure they are no longer on the all tab
8. Make sure you are not able to add or remove anyone from an anthology if you do use your normal nonadmin account.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Clicked on an anthology, and tried to switch the user tab, and got this: 

Screenshot 2020-04-29 15 51 30

**Comment by timdunn22** [comment]
Try this again it should work now.

**Comment by jamiefolsom** [comment]
Email search is case-sensitive; probably shouldn't be. See: http://cove-staging.herokuapp.com/anthologies/literature-201-section-b?utf8=%E2%9C%93&email=Jamie&tab=users

**Comment by jamiefolsom** [comment]
Let's include the user's name in the alert, rather than saying "the user"?

Screenshot 2020-04-29 16 25 39

**Comment by jamiefolsom** [comment]
Apart from those nits, the UI looks pretty good, @timdunn22 -- I will review code next.

**Comment by jamiefolsom** [comment]
OK, let's merge this one, @timdunn22

**Pull request merged**
