### PR TITLE
Made changes to several UI elements

### LINKED ISSUE #28: UI changes for COVE
- [x] Class/group nomenclature
- [x] Document editing phase nomenclature
- [x] Publishing process

### LINKED ISSUE #37: Remove figaro
Since heroku now provides config:push and config:pull, we should remove figaro.

### LINKED ISSUE #39: As a user, I want COVE and Studio to be easily navigable
We've discussed putting a navigational ribbon at top of both sites, with links to each.

### PR DESCRIPTION
**Pull request by jamiefolsom**
### What does this PR do?

- Makes group nomenclature configurable
- Adds snapshot preview
- Adjusts document phases
- Makes typekit configurable
- Makes navbar brand configurable

Closes #28
Closes #39 
Closes #37

### How to test

This PR is staged for review at: https://cove-studio-pr-40.herokuapp.com/ (note that the "View Deployment" button in the conversation thread below points there too).

You will need an account, with the role of teacher or admin, to see all features. Shoot me an email when you've created an account, and I will add those roles.

- Document phases: 
  1. Visit: https://cove-studio-pr-40.herokuapp.com/dashboard
  1. Click create new document (https://cove-studio-pr-40.herokuapp.com/documents/new)
  1. Note that available document phases are now: draft/annotatable/published/archived. *If you don't see those phases, it's likely due to your not having teacher or admin role. Let me know and I will fix that*.

- Group nomenclature:
  1. Visit: https://cove-studio-pr-40.herokuapp.com/dashboard and https://cove-studio-pr-40.herokuapp.com/users/edit
  1. Note that in both places, instead of being called "Classes" and "Groups", those entities are called "Covens" and "Cabals", just to demonstrate configurability.

- Snapshot preview: 
  1. Visit https://cove-studio-pr-40.herokuapp.com/documents/example
  1. Annotate. 
  1. Open the annotation filter sidebar, and click snapshot at the bottom.
  1. Visit https://cove-studio-pr-40.herokuapp.com/documents/example/preview
  1. Note that your annotations are visible.

- Typekit configurability
  1. In one browser window, open https://cove-studio-pr-40.herokuapp.com/documents/example/ 
  1. In another, open: https://cove-studio.herokuapp.com/documents/example/
  1. Note that the typeface used for the main document text on the first is different from that used on the second.
  1. Hit Option-Command-J on the keyboard to open the javascript console. Note that there is not an error regarding typekit not being enabled for this domain.

- Brand configurability
  1. In one browser window, visit: http://mit.annotationstudio.org; take note of the branding of the application at the top of all pages: Annotation Studio MIT (in MIT red color).
  1. In another browser window, visit: https://cove-studio-pr-40.herokuapp.com/; take note of the branding of the application at the top of all pages: NAVSA ... COVE Editions ... Cove Studio.

### CODE REVIEW

**Comment by SteveMarvin** [comment]
Not authorized to access my own preview, created with snapshot. 

Cannot access document example.

**Comment by jamiefolsom** [comment]
@SteveMarvin -- preview should now be working again on https://cove-studio-pr-40.herokuapp.com/. Thanks for your help today!

**Comment by SteveMarvin** [comment]
Preview only shows highlighting at this stage, this is as intended.

**Comment by SteveMarvin** [comment]
The following pages are properly branded for COVE:

https://cove-studio-pr-40.herokuapp.com/
https://cove-studio-pr-40.herokuapp.com/dashboard
https://cove-studio-pr-40.herokuapp.com/documents
https://cove-studio-pr-40.herokuapp.com/annotations
https://cove-studio-pr-40.herokuapp.com/groups
https://cove-studio-pr-40.herokuapp.com/users/edit
https://cove-studio-pr-40.herokuapp.com/users/password/new
https://cove-studio-pr-40.herokuapp.com/users/confirmation/new
https://cove-studio-pr-40.herokuapp.com/documents/new

The following page has proper header branding, but the content has not been converted:

https://cove-studio-pr-40.herokuapp.com/pages/terms

The following pages still have MIT branding, as they launch old links in new tabs:

http://www.annotationstudio.org/project/
http://www.annotationstudio.org/pedagogy/
http://www.annotationstudio.org/community/
http://www.annotationstudio.org/support/
http://www.annotationstudio.org/news/
http://support.annotationstudio.org/

**Comment by SteveMarvin** [comment]
Typekit configurability was tested by myself and Jamie last Thursday. The differences are subtle, and consist of one site calling the library and the other not. This is difficult to test explicitly without a strong differentiation in font, but this is implemented as requested by the client, so thumbs up!

**Comment by jamiefolsom** [comment]
👍  Thanks!

**Comment by SteveMarvin** [comment]
Regression: tough to test typekit without a review app, but everything else checks out. 👍

**Pull request merged**
