### PR TITLE
Ingested user, document, and most annotation data from COVE editions

### PR DESCRIPTION
**Pull request by jamiefolsom**
### What does this PR do?

Brings COVE data into Studio.

### How to test

1. Go to http://cove-staging-pr-85.herokuapp.com/
1. Log in (as an admin user -- let me know which account you're using and I will grant you permissions)
1. Go to http://cove-staging-pr-85.herokuapp.com/documents/
1. Click the "All" tab
1. Note that there are 10 or so documents; those are from COVE editions
1. Click on of them to view it
1. Click the gear menu at top right to open the annotation filters
1. Click "All" on the top filter, to see annotations made by all users.
1. Note that there are many, made by different users.

### What's not covered by this PR

- [ ] Ingestion of categories on annotations (will be covered by #88)
- [ ] Removal of unused JSON archive in snapshot
- [ ] Fix username in exported snapshots (#87)

### CODE REVIEW

**Comment by SteveMarvin** [comment]
So I'm not seeing what you are. I have admin, and I can see the ALL tab. But all of the documents there are in Mine. I see no additional documents in the ALL tab, and thus no annotations by other users.


cove documents

**Comment by jamiefolsom** [comment]
Ah! In this one instance, because this is a multi-tenant app, the URL is used to switch which data you see. I think I can fix that -- sec.

**Comment by jamiefolsom** [comment]
OK @SteveMarvin, try again at your convenience -- I think I got it sorted.

**Comment by SteveMarvin** [comment]
Looking good! I see many annotations. I'm accepting this. 👍  However, see related bug #89.

**Pull request merged**
