### PR TITLE
Implemented document search on the anthology show page

### LINKED ISSUE #207: Anthologies: on anthology show view, add document search and add feature
It should be possible to search for documents by title or author on the anthology show view (eg: http://cove-staging.herokuapp.com/anthologies/literature-201-section-b), and from search results list (maybe in a separate tab), click a single button to add that document to an anthology.

Let's try the search fields at top, under banner.

### PR DESCRIPTION
**Pull request by timdunn22**
# What this PR does
1. Allows users to search for documents (all documents) in the anthology show by author, edition, and title.
2. Allows users to see all the documents that belong to an anthology in the all tab of the anthology show
3. Allows users to add documents to an anthology 
4. Allows users to remove documents from an anthology if they are admins
3. Closes #207 
# Testing
1. Go to http://cove-staging.herokuapp.com/anthologies and select any anthology 
2. Search for a document by author, edition, or title
3. The search results tab should be active with your search results and pagination if there are more than 10 results
4. You can then try to remove a document from an anthology if it already is part of the anthology and see if you get a successful flash message after. (To see which documents are part of the anthology click the all tab)
5. Search for a document that is not a part of anthology and try to add it by checking the check box and clicking on add to anthology. You should then be given a successful flash message after which you will see the document in the all tab. As an example you can search for "Un" as the title.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@timdunn22 I can access the /anthologies route even when I am not logged in, which I shouldn't be able to. To reproduce, open this link in an incognito window in chrome: http://cove-staging.herokuapp.com/anthologies

**Comment by timdunn22** [comment]
Now the user can't go to any anthology related path without logging in.

**Comment by jamiefolsom** [comment]
On #3 from the cover letter -- they shouldn't be able to add documents if they're not the owner. Is that the case?

**Comment by timdunn22** [comment]
> On item 3 from the cover letter -- they shouldn't be able to add documents if they're not the owner. Is that the case?
@jamiefolsom 
The admin can't add documents to an anthology even if they are not the owner?

**Comment by SteveMarvin** [comment]
accepted

**Pull request merged**
