### PR TITLE
Change columns on the anthology show view documents list

### PR DESCRIPTION
**Pull request by timdunn22**
## What does this PR do?
1. Removed the editions column on anthology show
2. Added a vetted column on anthology show
3. Status column on anthology show is only available to admins

## How to test?
1. Login using your admin account
2. Go to the  http://cove-staging.herokuapp.com/anthologies
3. Click on an anthology
4. The Editions search and table column should be entirely gone.
5. The Status column must be present.
6. A vetted column should also be present.
7. Logout and Login as a non-admin.
8. Repeat step 2 and 3
9. The status column should not be present

### CODE REVIEW

**Comment by SteveMarvin** [comment]
When I go to Anthologies, I do not see a status or a vetted column, and several errors are generated in the console.  Editions search and column are gone.
image

**Comment by jamiefolsom** [comment]
@timdunn22 can you clarify your PR cover letter -- I think it reads as though Status column should be there for non-admins -- where the purpose of this PR is to make it unavailable.

**Comment by timdunn22** [comment]
@SteveMarvin Try this again.

**Comment by SteveMarvin** [comment]
I didn't see a status column as an admin, either.

**Comment by timdunn22** [comment]
@SteveMarvin I just tried and was able to see the status column on the anthology show. Try one more time please.

**Pull request merged**
