### PR TITLE
Fix user show issue

### LINKED ISSUE #196: Default route upon login shows 404

### PR DESCRIPTION
**Pull request by timdunn22**
### What does this PR do?

Closes #196 

### How to test

1. Go to http://cove-staging.herokuapp.com/
2. Log in
3. Don't see a 404 error.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@timdunn22 Can you edit the comment on this PR to explain what the problem was, and how this solves it? Thanks.

**Comment by jamiefolsom** [comment]
Hi @timdunn22 -- can you rebase this PR? (`git rebase -i origin/master`). Then you can force push to the `origin/user_search` branch to update the PR, and get it merged. 

Alternatively, just cherry pick the commit and close this PR -- either way. Thanks.

**Comment by SteveMarvin** [comment]
lol yup I can get in just fine.

**Comment by jamiefolsom** [comment]
Closing as fixed elsewhere.

**Pull request closed without merging**
